aider: Fix decompressing artifacts with non-existent relative paths.
# Aider chat conversation:

USER: Now I have the following error "Starting download of Fedora-Container-Base-Generic.x86_64-40-1.10.oci.tar.xz...
Downloaded /tmp/x86_64/Fedora-Container-Base-Generic.x86_64-40-1.10.oci.tar.xz
Decompressing x86_64/Fedora-Container-Base-Generic.x86_64-40-1.10.oci.tar.xz...
xz: x86_64/Fedora-Container-Base-Generic.x86_64-40-1.10.oci.tar.xz: No such file or directory
Traceback (most recent call last):
  File "/var/home/cverna/Documents/LLMs/download_fedora_container/download_artifacts.py", line 137, in <module>
    main(args.version, args.mini, args.output_dir)
  File "/var/home/cverna/Documents/LLMs/download_fedora_container/download_artifacts.py", line 127, in main
    decompress_artifact(output_path, version)
  File "/var/home/cverna/Documents/LLMs/download_fedora_container/download_artifacts.py", line 89, in decompress_artifact
    subprocess.run(["xz", "-d", artifact_path], check=True)
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['xz', '-d', 'x86_64/Fedora-Container-Base-Generic.x86_64-40-1.10.oci.tar.xz']' returned non-zero exit status 1.
"

ASSISTANT: The error you're encountering is due to the `decompress_artifact` function attempting to decompress a file using a relative path that does not exist in the current working directory of the script. To fix this, we need to ensure that the full path to the artifact is passed to the `xz` command within the `decompress_artifact` function.

We will modify the `download_artifacts.py` file to correct the path issue:

download_artifacts.py
```python
<<<<<<< SEARCH
        subprocess.run(["xz", "-d", artifact_path], check=True)
=======
        subprocess.run(["xz", "-d", os.path.join(os.getcwd(), artifact_path)], check=True)
>>>>>>> REPLACE
```

This change prepends the current working directory to the `artifact_path` before passing it to the `xz` command, ensuring that the full path is used and the file can be found correctly.

Signed-off-by: Clement Verna <cverna@tutanota.com>