aider: Fix indentation error in `download_artifacts.py` by correcting the indentation of the `soup` assignment line.
# Aider chat conversation:

USER: the script give the following error "  File "/var/home/cverna/Documents/LLMs/python-script/download_artifacts.py", line 20
    soup = BeautifulSoup(text, 'html.parser')
IndentationError: unexpected indent
"

ASSISTANT: To fix the indentation error in `download_artifacts.py`, we need to correct the indentation of the `soup` assignment line. Here is the *SEARCH/REPLACE* block to make this change:

download_artifacts.py
```python
<<<<<<< SEARCH
    text = response.text
        soup = BeautifulSoup(text, 'html.parser')
=======
    text = response.text
    soup = BeautifulSoup(text, 'html.parser')
>>>>>>> REPLACE
```

This change will correct the indentation and should resolve the `IndentationError`.

Signed-off-by: Clement Verna <cverna@tutanota.com>